name: CI/CD - Build and Push Docker Image

on:
  push:
    branches:
      - main  # يشتغل كل مرة تعمل push على main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node dependencies (optional)
        run: |
          if [ -f "package.json" ]; then
            npm install
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.am7soft }}
          password: ${{ secrets.1a2b3c4dHH!}}
 

      - name: Build Docker Image
        run: docker build -t ${{ secrets.am7soft }}/details-service:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.am7soft}}/details-service:latest
